# Shared Sphinx configuration for both language trees (zh/ and en/).
#
# Each language tree (source/zh/conf.py, source/en/conf.py) imports every
# name from this module via ``from _conf_base import *`` and then overrides
# the language-specific bits (``language``, ``html_title``).
#
# Layout:
#   docs/sphinx/source/
#   ├── _conf_base.py          <- this file
#   ├── _shared/_static/       <- shared static files (copied into each build)
#   ├── _shared/_templates/    <- shared templates (language switcher, etc.)
#   ├── zh/                    <- Chinese source tree (conf.py + documents)
#   └── en/                    <- English source tree (conf.py + documents)

from __future__ import annotations

import sys
from pathlib import Path

# -- Path anchors --------------------------------------------------------------
# _SOURCE_ROOT = docs/sphinx/source/ ; parents[0] = sphinx, [1] = docs, [2] = repo root

_SOURCE_ROOT = Path(__file__).resolve().parent
_SHARED = _SOURCE_ROOT / "_shared"
_REPO_ROOT = _SOURCE_ROOT.parents[2]

# NOTE: autodoc must import the *installed* pysparq (CI and local docs builds
# both run `pip install .` first); the installed copy is the only one carrying
# the compiled pysparq._core extension. Do NOT put the source tree PySparQ/ on
# sys.path here -- it has no _core, and every autoclass/autofunction in the
# API pages then fails to import. (autoapi still parses the source tree
# statically via autoapi_dirs, which is unaffected.)

# -- Project information -----------------------------------------------------

project = "SparQ"
copyright = "2021-2026, IAI-USTC-Quantum"
author = "IAI-USTC-Quantum"

# The version number is read dynamically: prefer the setuptools-scm version of the installed pysparq package,
# and fall back to "dev" when building the documentation standalone (pysparq not installed).
try:
    from importlib.metadata import version as _package_version

    release = _package_version("pysparq")
except Exception:
    release = "dev"

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "myst_parser",
    "sphinx_copybutton",
    "autoapi.extension",
    "nbsphinx",
    "breathe",
]

templates_path = [str(_SHARED / "_templates")]
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
]

# -- Options for HTML output -------------------------------------------------

html_theme = "furo"
html_static_path = [str(_SHARED / "_static")]

# Theme options for furo
html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "#2563eb",
        "color-brand-content": "#1d4ed8",
    },
    "dark_css_variables": {
        "color-brand-primary": "#3b82f6",
        "color-brand-content": "#60a5fa",
    },
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
    "source_repository": "https://github.com/IAI-USTC-Quantum/SparQSim/",
    "source_branch": "main",
    "source_directory": "docs/sphinx/source/",
}

# Language switcher in the sidebar (see _shared/_templates/sidebar/langswitch.html)
html_sidebars = {
    "**": [
        "sidebar/brand.html",
        "sidebar/langswitch.html",
        "sidebar/search.html",
        "sidebar/navigation.html",
    ],
}

# -- Options for MyST parser -------------------------------------------------
# https://myst-parser.readthedocs.io/en/latest/configuration.html

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_admonition",
    "html_image",
    "replacements",
    "smartquotes",
    "tasklist",
]

# Generate GitHub-style anchors for h1-h3 so that in-page TOC links
# resolve in both language trees (zh keeps CJK anchors, en gets ASCII ones)
myst_heading_anchors = 3

# -- Options for Breathe (C++ API via Doxygen XML) ----------------------------
# The XML is generated by docs/doxygen/Doxyfile (run automatically by the html
# target of docs/sphinx/Makefile, or by docs.yml in CI).

breathe_projects = {"SparQ": str(_SOURCE_ROOT.parents[1] / "doxygen" / "build" / "xml")}
breathe_default_project = "SparQ"

# -- Options for AutoAPI -----------------------------------------------------
# https://sphinx-autoapi.readthedocs.io/

autoapi_type = "python"
autoapi_dirs = [str(_REPO_ROOT / "PySparQ" / "pysparq")]
autoapi_root = "autoapi"
autoapi_file_patterns = ["*.pyi", "*.py"]
autoapi_generate_api_docs = True
# autoapi/index is added manually to the api/index toctree (both trees) with an
# explicit title, so it does not duplicate the hand-written "API Reference" entry
autoapi_add_toctree_entry = False
autoapi_options = [
    "members",
    "undoc-members",
    "show-inheritance",
    "show-module-summary",
    "imported-members",
]
autoapi_python_class_content = "both"
autoapi_member_order = "groupwise"
autoapi_keep_private_level = 0
autoapi_ignore = []

# -- Options for Intersphinx -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html

intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
}

# -- Options for Napoleon ----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_keyword = True
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# -- Options for Todo --------------------------------------------------------

todo_include_todos = True

# -- Copy button options -----------------------------------------------------

copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_line_continuation_character = "\\"
copybutton_here_doc_delimiter = "EOT"

# -- nbsphinx options --------------------------------------------------------
# https://nbsphinx.readthedocs.io/

nbsphinx_execute = "never"  # Disable execution: kernel dies on compile_operator cells
nbsphinx_timeout = 60
# Note: nbsphinx prolog/epilog templates use env.docname instead of docname
# in newer versions. We omit prolog for simplicity.
# compile_operator cells require pysparq and g++ in the Jupyter kernel environment,
# so notebooks are rendered as static content only (not executed).

# Notebook markdown cells intentionally link to sibling pages with static
# relative .html hrefs (nbsphinx markdown does not support Sphinx roles), so
# nbsphinx cannot map them to source documents and warns "File not found".
# These are false positives -- every emitted href is validated against the
# built HTML tree by the docs link checker instead.
suppress_warnings = ["nbsphinx.localfile"]
